on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # install dependencies, build, and test
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x' # Replace with specific Node version : 8.x, 10.x, 12.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run node-ng:build
        #npm run test --if-present
    
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ACTIONDEMO }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with: 
        app-name: NodeFunctionGH # Replace with your Function app name
        package: '.'  #default value is entire repo
        # If your function app project is not located in your repository's root
        # Please consider prefixing the project path in this package parameter
        
    - name: 'Echo the published functionapp url'
      run: |
        echo "${{ steps.fa.outputs.app-url }}"
